line.bot:
  channel-token: ${CHANNEL_TOKEN}
  channel-secret: ${CHANNEL_SECRET}
  handler.path: /callback

spring:
  jpa:
    database: POSTGRESQL
    open-in-view: True
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    connectionProperties: useUnicode=true;characterEncoding=utf-8;
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
